CREATE TABLE OdinParts.UTENTE(
    "USERNAME" VARCHAR(20) PRIMARY KEY NOT NULL ENABLE,
    "NOME" VARCHAR(40) NOT NULL ENABLE,
    "COGNOME" VARCHAR(40) NOT NULL ENABLE,
    "MAIL" VARCHAR(30) NOT NULL ENABLE,
    "PASSWORD" VARCHAR(20) NOT NULL ENABLE,
    "VOTO_SPED" DECIMAL(4,2) DEFAULT 0 NOT NULL ENABLE,
    "VOTO_COMM" DECIMAL(4,2) DEFAULT 0 NOT NULL ENABLE,
    "VOTO_DESC" DECIMAL(4,2) DEFAULT 0 NOT NULL ENABLE,
    CHECK (voto_sped BETWEEN 0.0 AND 10.0),
    CHECK (voto_desc BETWEEN 0.0 AND 10.0),
    CHECK (voto_comm BETWEEN 0.0 AND 10.0),
    "VOTO" DECIMAL(4,2) AS ((voto_comm+voto_sped+voto_desc)/3) ENABLE,
    "FEEDBACK_N" INT DEFAULT 0 NOT NULL ENABLE,
    "REGISTRATO" DATE NOT NULL ENABLE
);

CREATE TABLE "ODINPARTS"."INDIRIZZI" (
    "VIA" VARCHAR(30) NOT NULL ENABLE,
    "CIVICO" INT NOT NULL ENABLE,
    "CITTÀ" VARCHAR(20) NOT NULL ENABLE,
    "CAP" INT NOT NULL ENABLE,
    "STATO" VARCHAR(20) NOT NULL ENABLE,
    "USERNAME" VARCHAR(20) NOT NULL ENABLE,
    PRIMARY KEY ("USERNAME","VIA","CIVICO","CITTÀ","CAP","STATO"),
        CONSTRAINT USRN_FK
		FOREIGN KEY(USERNAME) REFERENCES UTENTE(USERNAME)
);

CREATE TABLE "ODINPARTS"."RICAMBIO" (
    "ID_RICAMBIO" VARCHAR(20) PRIMARY KEY NOT NULL ENABLE,
    "NOME" VARCHAR(60) NOT NULL ENABLE,
    "PRODUTTORE" VARCHAR(20) NOT NULL ENABLE,
    "CATEGORIA" VARCHAR(60) NOT NULL ENABLE,
    "N_SERIALE" VARCHAR(20) NOT NULL ENABLE,
    "GIACENZA" INT NOT NULL ENABLE,
    "DESCRIZIONE" VARCHAR(700) NOT NULL ENABLE,
    "FASCIA" VARCHAR(12) NOT NULL ENABLE,
    "DIMENSIONI" VARCHAR(20) NOT NULL ENABLE,
    "MATERIALE" VARCHAR(30) NOT NULL ENABLE,
    "PREZZO" DECIMAL(8,2) NOT NULL ENABLE,
    "URL_FOTO" VARCHAR(2083) NOT NULL ENABLE
);

CREATE TABLE "ODINPARTS"."MODELLO_AUTO"(
	"AUTO_ID" VARCHAR(30) PRIMARY KEY NOT NULL,
    "CASA_PROD" VARCHAR(15) NOT NULL,
    "ANNO" VARCHAR(10) NOT NULL,
    "VERSIONE" VARCHAR(8),
    "CARBURANTE" VARCHAR(10) NOT NULL,
    "MOTORE" VARCHAR(3) NOT NULL,
    "CILINDRATA" SMALLINT NOT NULL
 );

/***************************************/
/********SEQUENZA PER IMPLEMENTARE******/
/****AUTO_INCREMENT IN******************/
/******************CHIAVE PRIMARIA******/
/***************************************/
CREATE SEQUENCE ODINPARTS.INC_SEQ
START WITH 1
INCREMENT BY 1;
/***************************************/

CREATE TABLE "ODINPARTS"."ORDINE"(
	"ID_ORDINE" INT DEFAULT "ODINPARTS".INC_SEQ.NEXTVAL PRIMARY KEY NOT NULL,
    "ACQUIRENTE" VARCHAR(20) NOT NULL,
    "CARTA" CHAR(16) NOT NULL,
    "DATA_PAY" TIMESTAMP NOT NULL,
    "TOTALE" DECIMAL(6,2) NOT NULL,
    CONSTRAINT ORDER_FK
    	FOREIGN KEY("ACQUIRENTE") REFERENCES UTENTE("USERNAME")
 );

CREATE TABLE "ODINPARTS"."RECENSIONE"(
	"COMMENTO" VARCHAR(1000) NOT NULL,
    "DATA" TIMESTAMP NOT NULL,
    "VOTAZIONE" INT NOT NULL,
    "USERNAME" VARCHAR(20) NOT NULL,
    "ID_RICAMBIO" VARCHAR(20) NOT NULL,
    CHECK ("VOTAZIONE" BETWEEN 0 AND 10),
    PRIMARY KEY("USERNAME","ID_RICAMBIO"),
    CONSTRAINT REV_FK_0
    	FOREIGN KEY ("USERNAME") REFERENCES UTENTE("USERNAME"),		
	CONSTRAINT REV_FK_1
    	FOREIGN KEY ("ID_RICAMBIO") REFERENCES RICAMBIO("ID_RICAMBIO")
			ON DELETE CASCADE
 );
 
CREATE TABLE "ODINPARTS"."CARTA_C"(
	"NUMERO" CHAR(16) PRIMARY KEY NOT NULL,
    "NOME_TITOLARE" VARCHAR(20) NOT NULL,
    "COGNOME_TITOLARE" VARCHAR(20) NOT NULL,
    "CVV" CHAR(3) NOT NULL,
    "SCADENZA" CHAR(6) NOT NULL,
    "USERNAME" VARCHAR(20) NOT NULL,
    CONSTRAINT CARD_C
		FOREIGN KEY("USERNAME") REFERENCES UTENTE("USERNAME")
			ON DELETE CASCADE			/*SE L'UTENTE È CANCELLATO, LE INFORMAZIONI DELLA CARTA NON SONO RILEVANTI*/
 );
 
CREATE TABLE "ODINPARTS"."SPEDIZIONE"(
	"ID_SPED" VARCHAR(15) PRIMARY KEY NOT NULL,
    "CORRIERE" VARCHAR(20) NOT NULL,
    "DATA_INVIO" DATE NOT NULL,
    "DATA_CONSEGNA" DATE NOT NULL,
    "ID_ORDINE" INT NOT NULL,
    CONSTRAINT SHPMT_FK
		FOREIGN KEY("ID_ORDINE") REFERENCES ORDINE("ID_ORDINE")
			ON DELETE CASCADE			/*SE L'ORDINE È CANCELLATO, FREGA NIENTE DELLA SPEDIZIONE*/	
);

CREATE TABLE "ODINPARTS"."LISTA_COMP"(
	"AUTO_ID"	VARCHAR(30) NOT NULL,
    "ID_RICAMBIO" VARCHAR(20) NOT NULL,
    PRIMARY KEY("AUTO_ID","ID_RICAMBIO"),
	CONSTRAINT LIST_C_0
		FOREIGN KEY("AUTO_ID") REFERENCES MODELLO_AUTO("AUTO_ID")
			ON DELETE CASCADE,
	CONSTRAINT LIST_C_1
		FOREIGN KEY("ID_RICAMBIO") REFERENCES RICAMBIO("ID_RICAMBIO")
			ON DELETE CASCADE
);

CREATE TABLE "ODINPARTS"."ACQUISTATI"(
	"ACQUIRENTE" VARCHAR(20) NOT NULL,
    "ID_RICAMBIO" VARCHAR(20) NOT NULL,
    "QTA" INT NOT NULL,
    PRIMARY KEY("ACQUIRENTE","ID_RICAMBIO"),
    CONSTRAINT ACQUISTI_C_0
		FOREIGN KEY("ACQUIRENTE") REFERENCES UTENTE("USERNAME"),
	CONSTRAINT ACQUISTI_C_1
		FOREIGN KEY("ID_RICAMBIO") REFERENCES RICAMBIO("ID_RICAMBIO")
);

CREATE TABLE "ODINPARTS"."VENDUTI"(
	"VENDITORE"VARCHAR(20) NOT NULL,
    "ID_RICAMBIO" VARCHAR(20) NOT NULL,
    "QTA" INT NOT NULL,
    PRIMARY KEY("VENDITORE","ID_RICAMBIO"),
	CONSTRAINT VENDUTI_C_0
		FOREIGN KEY("VENDITORE") REFERENCES UTENTE("USERNAME"),
	CONSTRAINT VENDUTI_C_1	
		FOREIGN KEY("ID_RICAMBIO") REFERENCES RICAMBIO("ID_RICAMBIO")
);

CREATE TABLE "ODINPARTS"."VENDITE"(
	"VENDITORE"VARCHAR(20) NOT NULL,
    "ID_ORDINE" INT NOT NULL,
    PRIMARY KEY("VENDITORE","ID_ORDINE"),
    CONSTRAINT VENDITE_C_0
		FOREIGN KEY("VENDITORE") REFERENCES UTENTE("USERNAME"),
	CONSTRAINT VENDITE_C_1
		FOREIGN KEY("ID_ORDINE") REFERENCES ORDINE("ID_ORDINE")
);

CREATE TABLE "ODINPARTS"."VOTI"(
	"ACQUIRENTE" VARCHAR(20) NOT NULL,
	"VENDITORE" VARCHAR(20) NOT NULL,
	"FEEDBACK" VARCHAR(80) NOT NULL,
    PRIMARY KEY("ACQUIRENTE","VENDITORE"),
    CONSTRAINT FEEDBACK_C_0
		FOREIGN KEY("ACQUIRENTE") REFERENCES UTENTE("USERNAME"),
	CONSTRAINT FEEDBACK_C_1
		FOREIGN KEY("VENDITORE") REFERENCES UTENTE("USERNAME")
);

CREATE TABLE "ODINPARTS"."RIC_ORD"(
	"ID_ORDINE" INT NOT NULL,
    "ID_RICAMBIO" VARCHAR(20) NOT NULL,
    "QTA" INT NOT NULL,
    PRIMARY KEY("ID_ORDINE","ID_RICAMBIO"),
    CONSTRAINT RIC_ORD_0
		FOREIGN KEY("ID_ORDINE") REFERENCES ORDINE("ID_ORDINE"),
	CONSTRAINT RIC_ORD_1
		FOREIGN KEY("ID_RICAMBIO") REFERENCES RICAMBIO("ID_RICAMBIO")
);


